version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9999:9090"
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring:/config
    command:
      - "--config.file=/config/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  aesm:
    build:
      dockerfile: ./docker/aesm.Dockerfile
      context: .
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    restart: always

  hw-node:
    container_name: swisstronik_hw_node
    build:
      dockerfile: ./docker/node.Dockerfile
      target: hw-node
      context: .
      args:
        - SGX_MODE=HW
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    depends_on:
      - aesm
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "8535:8535"
      - "8546:8546"
      - "8999:8999"
    command: swisstronikd start
    restart: always

  local-node:
    container_name: swisstronik_local
    build:
      dockerfile: ./docker/node.Dockerfile
      target: local-node
      context: .
      args:
        - SGX_MODE=SW
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "8535:8535"
      - "8546:8546"
      - "8999:8999"
    environment:
      - SGX_MODE=SW
    command: "swisstronikd start --minimum-gas-prices=0uswtr --json-rpc.api eth,txpool,personal,net,debug,web3 --api.enable --enclave.address 0.0.0.0:8999 --json-rpc.address 0.0.0.0:8535 --json-rpc.ws-address 0.0.0.0:8546"
    restart: always

  full-node:
    container_name: swtr_full_node
    build: 
      dockerfile: ./docker/node.Dockerfile
      target: full-node
      context: .
      args:
        - SGX_MODE=SW
        - NODE_URL=${NODE_URL}
        - MONIKER=${MONIKER}
        - CHAIN_ID=${CHAIN_ID}
        - SEED_NODE=${SEED_NODE}
    ports: 
      - "26656-26657:26656-26657"
      - "26660:26660"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
    env_file:
      - docker.env
    command: "swisstronikd start --json-rpc.api eth,txpool,net,debug,web3 --json-rpc.address 0.0.0.0:8545 --json-rpc.ws-address 0.0.0.0:8546 --minimum-gas-prices 0uswtr --home /swisstronik --p2p.seeds=${SEED_NODE} --enclave.enable=false --rpc.laddr=tcp://0.0.0.0:26657 --metrics --pruning=nothing --api.enable"    