[package]
name = "evm-precompile-curve25519"
version = "1.0.0-dev"
edition = "2021"
description = "Curve25519 elliptic curve precompiles for EVM"

[dependencies]
curve25519-dalek = { version = "4.0.0-pre.2", default-features = false, features = ["alloc", "u64_backend"] }

# Precompile-std
precompile-std = { version = "1.0.0-dev", path = "../precompile-std" }